name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

  api_check:
    runs-on: ubuntu-latest
    needs: build
    env:
      CLI_HEALTH_TOKEN: ${{ secrets.CLI_HEALTH_TOKEN }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Next.js
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run SDK API checks
        run: APP_URL=http://localhost:3000 node scripts/sdk-api-check.mjs

      - name: Provider health with transient keys (POST)
        if: ${{ env.CLI_HEALTH_TOKEN != '' }}
        run: |
          curl -s -X POST "http://localhost:3000/api/provider-health?token=${CLI_HEALTH_TOKEN}" \
            -H 'Content-Type: application/json' \
            -d "{\"openai\":\"${OPENAI_KEY}\",\"anthropic\":\"${ANTHROPIC_KEY}\",\"google\":\"${GOOGLE_KEY}\"}" | tee provider-health.json
          cat provider-health.json | jq -e '.ok == true'

  e2e:
    runs-on: ubuntu-latest
    needs: api_check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Next.js
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: APP_URL=http://localhost:3000 npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report


